services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --api.dashboard=false
    ports:
      - "80:80"
      - "443:443"

  postcard-auth:
    container_name: postcard-auth
    image: ghcr.io/keil0/postcard-backend:latest
    restart: always
    env_file: .env
    networks:
      - traefik_network
    volumes:
      - ./uploads:/usr/src/app/build/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postcard-auth.rule=Host(`postcard.innocean.app`) && PathPrefix(`/auth`)"
      # SSL
      - "traefik.http.routers.postcard-auth.tls=true"
      - "traefik.http.routers.postcard-auth.entrypoints=websecure"
      # Middleware to strip the /auth prefix
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      # Apply middlewares
      - "traefik.http.routers.postcard-auth.middlewares=auth-strip"

  postcard-app:
    container_name: postcard-app
    image: ghcr.io/keil0/postcard-frontend:latest
    restart: always
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postcard-app.rule=Host(`postcard.innocean.app`)"
      # SSL
      - "traefik.http.routers.postcard-app.entrypoints=websecure"
      - "traefik.http.routers.postcard-app.tls=true"
      # Authentification middleware
      - "traefik.http.middlewares.auth-forward.forwardauth.address=https://postcard.innocean.app/auth"
      - "traefik.http.middlewares.auth-forward.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.auth-forward.forwardauth.authResponseHeaders=X-Forwarded-User"
      # Apply middlewares
      - "traefik.http.routers.postcard-app.middlewares=auth-forward@docker"

networks:
  traefik_network:
    driver: bridge