services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"

  postcard-auth:
    container_name: postcard-auth
    image: ghcr.io/keil0/easy-email-auth:latest
    restart: always
    env_file: .env
    networks:
      - traefik_network
    volumes:
      - ./uploads:/usr/src/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postcard-auth.rule=Host(`postcard.innocean.app`) && PathPrefix(`/auth`)"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.postcard-auth.middlewares=auth-strip"
      - "traefik.http.routers.postcard-auth.entrypoints=websecure"
      - "traefik.http.routers.postcard-auth.tls=true"

  postcard-app:
    container_name: postcard-app
    image: ghcr.io/keil0/easy-email:latest
    restart: always
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postcard-app.rule=Host(`postcard.innocean.app`)"
      - "traefik.http.routers.postcard-app.entrypoints=websecure"
      - "traefik.http.routers.postcard-app.tls=true"
      # Authentication
      - "traefik.http.middlewares.auth-forward.forwardauth.address=https://postcard.innocean.app/auth"
      - "traefik.http.middlewares.auth-forward.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.auth-forward.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.routers.postcard-app.middlewares=auth-forward@docker"

networks:
  traefik_network:
    driver: bridge