export enum InnoceanBlocksType {
  TOP = 'TOP',
  RESPONSIVE_IMAGE = 'RESPONSIVE_IMAGE',
  BUTTON = 'BUTTON',
  TEXT_BLOCK = 'TEXT_BLOCK',
  TITLE_IMAGE_BLOCK = 'TITLE_IMAGE_BLOCK',
  TWO_COLUMNS = 'TWO_COLUMNS',
}