name: "Deploy demo"

on:
  push:
    branches: [master]

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build image and push to registry
        uses: docker/build-push-action@v2
        with:
          # Define the Dockerfile file name
          file: Dockerfile
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Build arguments
          build-args: |
            NODE_ENV=production
          # Note: tags has to be all lower-case
          tags: ghcr.io/${{ github.repository_owner }}/easy-email:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}